model_name=CATS

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 96 \
  --d_layers 3 \
  --dec_in 862 \
  --des 'Exp' \
  --itr 1 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --QAM_end 0.2 \
  --lradj TST \
  --batch_size 32 \
  --train_epochs 100 \
  --patience 20 \
  --query_independence \
  --use_multi_gpu

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 192 \
  --d_layers 3 \
  --dec_in 862 \
  --des 'Exp' \
  --itr 1 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --QAM_end 0.3 \
  --lradj TST \
  --batch_size 32 \
  --train_epochs 100 \
  --patience 20 \
  --query_independence \
  --use_multi_gpu

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 336 \
  --d_layers 3 \
  --dec_in 321 \
  --des 'Exp' \
  --itr 1 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --QAM_end 0.5 \
  --lradj TST \
  --batch_size 32 \
  --train_epochs 100 \
  --patience 20 \
  --query_independence \
  --use_multi_gpu

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_512_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 512 \
  --pred_len 720 \
  --d_layers 3 \
  --dec_in 862 \
  --des 'Exp' \
  --itr 1 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --QAM_end 0.7 \
  --lradj TST \
  --batch_size 32 \
  --train_epochs 100 \
  --patience 20 \
  --query_independence \
  --use_multi_gpu